
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductoService", targetNamespace = "http://ws/", wsdlLocation = "http://DESKTOP-PJRS1QE:8080/ProductoService/ProductoService?WSDL")
public class ProductoService_Service
    extends Service
{

    private final static URL PRODUCTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTOSERVICE_EXCEPTION;
    private final static QName PRODUCTOSERVICE_QNAME = new QName("http://ws/", "ProductoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-PJRS1QE:8080/ProductoService/ProductoService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTOSERVICE_WSDL_LOCATION = url;
        PRODUCTOSERVICE_EXCEPTION = e;
    }

    public ProductoService_Service() {
        super(__getWsdlLocation(), PRODUCTOSERVICE_QNAME);
    }

    public ProductoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTOSERVICE_QNAME, features);
    }

    public ProductoService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTOSERVICE_QNAME);
    }

    public ProductoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTOSERVICE_QNAME, features);
    }

    public ProductoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductoService
     */
    @WebEndpoint(name = "ProductoServicePort")
    public ProductoService getProductoServicePort() {
        return super.getPort(new QName("http://ws/", "ProductoServicePort"), ProductoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductoService
     */
    @WebEndpoint(name = "ProductoServicePort")
    public ProductoService getProductoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ProductoServicePort"), ProductoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTOSERVICE_EXCEPTION!= null) {
            throw PRODUCTOSERVICE_EXCEPTION;
        }
        return PRODUCTOSERVICE_WSDL_LOCATION;
    }

}
